export const GET_POSTS_START = 'FIREBASE/GET_POSTS_START';
export const GET_POSTS_SUCCEED = 'FIREBASE/GET_POSTS_SUCCEED';
export const GET_POSTS_FAIL = 'FIREBASE/GET_POSTS_FAIL';

export const GET_RECOMMENDATION_START = 'FIREBASE/GET_RECOMMENDATION_START';
export const GET_RECOMMENDATION_SUCCEED = 'FIREBASE/GET_RECOMMENDATION_SUCCEED';
export const GET_RECOMMENDATION_FAIL = 'FIREBASE/GET_RECOMMENDATION_FAIL';
